language: java
sudo: false
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
  - openjdk6
script:
  mvn install -DskipTests=true -Dgpg.skip=true
  mvn test
  mvn clean verify
after_success:
after_failure:
